name: "PyLoweringContext.26"
entry_computation_name: "PyLoweringContext.26"
computations {
  name: "Hlo<locals>NkiCustomCall.9"
  instructions {
    name: "p0.10"
    opcode: "parameter"
    shape {
      element_type: BF16
      dimensions: 1
      dimensions: 2048
      layout {
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    id: 10
  }
  instructions {
    name: "p1.11"
    opcode: "parameter"
    shape {
      element_type: BF16
      dimensions: 1
      dimensions: 2048
      layout {
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    parameter_number: 1
    id: 11
  }
  instructions {
    name: "p2.12"
    opcode: "parameter"
    shape {
      element_type: F32
      dimensions: 2048
      dimensions: 128
      layout {
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    parameter_number: 2
    id: 12
  }
  instructions {
    name: "p3.13"
    opcode: "parameter"
    shape {
      element_type: BF16
      dimensions: 128
      dimensions: 2048
      dimensions: 384
      layout {
        minor_to_major: 2
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    parameter_number: 3
    id: 13
  }
  instructions {
    name: "p4.14"
    opcode: "parameter"
    shape {
      element_type: BF16
      dimensions: 128
      dimensions: 192
      dimensions: 2048
      layout {
        minor_to_major: 2
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    parameter_number: 4
    id: 14
  }
  instructions {
    name: "custom-call.15"
    opcode: "custom-call"
    shape {
      element_type: BF16
      dimensions: 1
      dimensions: 2048
      layout {
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    custom_call_target: "AwsNeuronCustomNativeKernel"
    id: 15
    operand_ids: 10
    operand_ids: 11
    operand_ids: 12
    operand_ids: 13
    operand_ids: 14
    backend_config: "eyJmdW5jX25hbWUiOiAidGVzdF92MzBjX3NpbXVsYXRlLl92MzBjX21vZV9yYXdfbG5jMCIsICJwbGF0Zm9ybV90YXJnZXQiOiA0LCAia2VybmVsX2Zvcm1hdCI6ICJiaXIiLCAia2VybmVsX3ZlcnNpb24iOiAxLCAia2xpcl9iaW5hcnkiOiB7ImJpbmFyeSI6ICIvdmFyL3RtcC9uZXVyb24tY29tcGlsZS1jYWNoZS9ua2lfMC4zLjArMjM5Mjg3MjE3NTQuZzE4YWExMjcxLzk2YTZhZjVmMmNmNjY3MGUvdGVzdF92MzBjX3NpbXVsYXRlLl92MzBjX21vZV9yYXdfbG5jMF85NmE2YWY1ZjJjZjY2NzBlLmpzb24iLCAiaW5wdXRfbmFtZXMiOiBbImlucCIsICJnYW1tYSIsICJyb3V0ZXJfdyIsICJnYXRlX3VwX3ciLCAiZG93bl93Il0sICJvdXRwdXRfbmFtZXMiOiBbIm91dHB1dF8wIl0sICJ2ZXJzaW9uX2lkZW50aWZpZXIiOiAiIiwgImFsaWFzZXMiOiBbXX0sICJncmlkIjogMiwgImhhc19jb2xsZWN0aXZlcyI6IGZhbHNlLCAibWFjX2NvdW50IjogMTM1MDA0MTZ9"
  }
  program_shape {
    parameters {
      element_type: BF16
      dimensions: 1
      dimensions: 2048
      layout {
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    parameters {
      element_type: BF16
      dimensions: 1
      dimensions: 2048
      layout {
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    parameters {
      element_type: F32
      dimensions: 2048
      dimensions: 128
      layout {
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    parameters {
      element_type: BF16
      dimensions: 128
      dimensions: 2048
      dimensions: 384
      layout {
        minor_to_major: 2
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    parameters {
      element_type: BF16
      dimensions: 128
      dimensions: 192
      dimensions: 2048
      layout {
        minor_to_major: 2
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    result {
      element_type: BF16
      dimensions: 1
      dimensions: 2048
      layout {
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    parameter_names: "p0"
    parameter_names: "p1"
    parameter_names: "p2"
    parameter_names: "p3"
    parameter_names: "p4"
  }
  id: 9
  root_id: 15
}
computations {
  name: "<locals>NkiCustomCall.16"
  instructions {
    name: "p0.17"
    opcode: "parameter"
    shape {
      element_type: BF16
      dimensions: 1
      dimensions: 2048
      layout {
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    metadata {
    }
    id: 17
    frontend_attributes {
    }
  }
  instructions {
    name: "p1.18"
    opcode: "parameter"
    shape {
      element_type: BF16
      dimensions: 1
      dimensions: 2048
      layout {
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    metadata {
    }
    parameter_number: 1
    id: 18
    frontend_attributes {
    }
  }
  instructions {
    name: "p2.19"
    opcode: "parameter"
    shape {
      element_type: F32
      dimensions: 2048
      dimensions: 128
      layout {
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    metadata {
    }
    parameter_number: 2
    id: 19
    frontend_attributes {
    }
  }
  instructions {
    name: "p3.20"
    opcode: "parameter"
    shape {
      element_type: BF16
      dimensions: 128
      dimensions: 2048
      dimensions: 384
      layout {
        minor_to_major: 2
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    metadata {
    }
    parameter_number: 3
    id: 20
    frontend_attributes {
    }
  }
  instructions {
    name: "p4.21"
    opcode: "parameter"
    shape {
      element_type: BF16
      dimensions: 128
      dimensions: 192
      dimensions: 2048
      layout {
        minor_to_major: 2
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    metadata {
    }
    parameter_number: 4
    id: 21
    frontend_attributes {
    }
  }
  instructions {
    name: "call.22"
    opcode: "call"
    shape {
      element_type: BF16
      dimensions: 1
      dimensions: 2048
      layout {
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    metadata {
    }
    id: 22
    operand_ids: 17
    operand_ids: 18
    operand_ids: 19
    operand_ids: 20
    operand_ids: 21
    called_computation_ids: 9
    frontend_attributes {
    }
  }
  program_shape {
    parameters {
      element_type: BF16
      dimensions: 1
      dimensions: 2048
      layout {
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    parameters {
      element_type: BF16
      dimensions: 1
      dimensions: 2048
      layout {
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    parameters {
      element_type: F32
      dimensions: 2048
      dimensions: 128
      layout {
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    parameters {
      element_type: BF16
      dimensions: 128
      dimensions: 2048
      dimensions: 384
      layout {
        minor_to_major: 2
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    parameters {
      element_type: BF16
      dimensions: 128
      dimensions: 192
      dimensions: 2048
      layout {
        minor_to_major: 2
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    result {
      element_type: BF16
      dimensions: 1
      dimensions: 2048
      layout {
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    parameter_names: "p0"
    parameter_names: "p1"
    parameter_names: "p2"
    parameter_names: "p3"
    parameter_names: "p4"
  }
  id: 16
  root_id: 22
}
computations {
  name: "PyLoweringContext.26"
  instructions {
    name: "p1"
    opcode: "parameter"
    shape {
      element_type: BF16
      dimensions: 128
      dimensions: 192
      dimensions: 2048
      layout {
        minor_to_major: 2
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    metadata {
      op_type: "xla__device_data"
      op_name: "KernelMoEModule[.1]/aten.view.default/xla__device_data"
      source_file: "/opt/aws_neuronx_venv_pytorch_2_9_nxd_inference/lib/python3.12/site-packages/torch/nn/modules/module.py"
      source_line: 1786
      stack_frame_id: 9
    }
    parameter_number: 1
    id: 1
    frontend_attributes {
    }
  }
  instructions {
    name: "p2"
    opcode: "parameter"
    shape {
      element_type: BF16
      dimensions: 128
      dimensions: 2048
      dimensions: 384
      layout {
        minor_to_major: 2
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    metadata {
      op_type: "xla__device_data"
      op_name: "KernelMoEModule[.1]/aten.view.default/xla__device_data"
      source_file: "/opt/aws_neuronx_venv_pytorch_2_9_nxd_inference/lib/python3.12/site-packages/torch/nn/modules/module.py"
      source_line: 1786
      stack_frame_id: 9
    }
    parameter_number: 2
    id: 2
    frontend_attributes {
    }
  }
  instructions {
    name: "p3"
    opcode: "parameter"
    shape {
      element_type: F32
      dimensions: 128
      dimensions: 2048
      layout {
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    metadata {
      op_type: "xla__device_data"
      op_name: "KernelMoEModule[.1]/aten.permute.default/xla__device_data"
      source_file: "/opt/aws_neuronx_venv_pytorch_2_9_nxd_inference/lib/python3.12/site-packages/torch/nn/modules/module.py"
      source_line: 1786
      stack_frame_id: 9
    }
    parameter_number: 3
    id: 3
    frontend_attributes {
    }
  }
  instructions {
    name: "transpose.4"
    opcode: "transpose"
    shape {
      element_type: F32
      dimensions: 2048
      dimensions: 128
      layout {
        minor_to_major: 0
        minor_to_major: 1
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    metadata {
      op_type: "aten__permute"
      op_name: "KernelMoEModule[.1]/aten.permute.default/aten__permute"
      source_file: "/opt/aws_neuronx_venv_pytorch_2_9_nxd_inference/lib/python3.12/site-packages/torch/nn/modules/module.py"
      source_line: 1786
      stack_frame_id: 9
    }
    dimensions: 1
    dimensions: 0
    id: 4
    operand_ids: 3
    frontend_attributes {
    }
  }
  instructions {
    name: "p4"
    opcode: "parameter"
    shape {
      element_type: BF16
      dimensions: 2048
      layout {
        minor_to_major: 0
      }
      is_dynamic_dimension: false
    }
    metadata {
      op_type: "xla__device_data"
      op_name: "KernelMoEModule[.1]/aten.unsqueeze.default/xla__device_data"
      source_file: "/opt/aws_neuronx_venv_pytorch_2_9_nxd_inference/lib/python3.12/site-packages/torch/nn/modules/module.py"
      source_line: 1786
      stack_frame_id: 9
    }
    parameter_number: 4
    id: 5
    frontend_attributes {
    }
  }
  instructions {
    name: "reshape.6"
    opcode: "reshape"
    shape {
      element_type: BF16
      dimensions: 1
      dimensions: 2048
      layout {
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    metadata {
      op_type: "aten__as_strided"
      op_name: "KernelMoEModule[.1]/aten.unsqueeze.default/aten__as_strided"
      source_file: "/opt/aws_neuronx_venv_pytorch_2_9_nxd_inference/lib/python3.12/site-packages/torch/nn/modules/module.py"
      source_line: 1786
      stack_frame_id: 9
    }
    id: 6
    operand_ids: 5
    frontend_attributes {
    }
  }
  instructions {
    name: "p0"
    opcode: "parameter"
    shape {
      element_type: BF16
      dimensions: 1
      dimensions: 1
      dimensions: 2048
      layout {
        minor_to_major: 2
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    metadata {
      op_type: "xla__device_data"
      op_name: "aten._to_copy.default/xla__device_data"
      source_file: "/opt/aws_neuronx_venv_pytorch_2_9_nxd_inference/lib/python3.12/site-packages/torch_neuronx/xla_impl/hlo_conversion.py"
      source_line: 601
      stack_frame_id: 6
    }
    id: 7
    frontend_attributes {
    }
  }
  instructions {
    name: "reshape.8"
    opcode: "reshape"
    shape {
      element_type: BF16
      dimensions: 1
      dimensions: 2048
      layout {
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    metadata {
      op_type: "aten__view"
      op_name: "KernelMoEModule[.1]/aten.view.default/aten__view"
      source_file: "/opt/aws_neuronx_venv_pytorch_2_9_nxd_inference/lib/python3.12/site-packages/torch/nn/modules/module.py"
      source_line: 1786
      stack_frame_id: 9
    }
    id: 8
    operand_ids: 7
    frontend_attributes {
    }
  }
  instructions {
    name: "call.23"
    opcode: "call"
    shape {
      element_type: BF16
      dimensions: 1
      dimensions: 2048
      layout {
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    metadata {
      op_type: "xla___op_<locals>NkiCustomCall"
      op_name: "KernelMoEModule[.1]/aten.view.default/xla___op_<locals>NkiCustomCall"
      source_file: "/opt/aws_neuronx_venv_pytorch_2_9_nxd_inference/lib/python3.12/site-packages/torch/nn/modules/module.py"
      source_line: 1786
      stack_frame_id: 9
    }
    id: 23
    operand_ids: 8
    operand_ids: 6
    operand_ids: 4
    operand_ids: 2
    operand_ids: 1
    called_computation_ids: 16
    frontend_attributes {
    }
  }
  instructions {
    name: "reshape.24"
    opcode: "reshape"
    shape {
      element_type: BF16
      dimensions: 1
      dimensions: 1
      dimensions: 2048
      layout {
        minor_to_major: 2
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    metadata {
      op_type: "aten__view"
      op_name: "KernelMoEModule[.1]/aten.view.default/aten__view"
      source_file: "/opt/aws_neuronx_venv_pytorch_2_9_nxd_inference/lib/python3.12/site-packages/torch/nn/modules/module.py"
      source_line: 1786
      stack_frame_id: 9
    }
    id: 24
    operand_ids: 23
    frontend_attributes {
    }
  }
  instructions {
    name: "tuple.25"
    opcode: "tuple"
    shape {
      element_type: TUPLE
      tuple_shapes {
        element_type: BF16
        dimensions: 1
        dimensions: 1
        dimensions: 2048
        layout {
          minor_to_major: 2
          minor_to_major: 1
          minor_to_major: 0
        }
        is_dynamic_dimension: false
        is_dynamic_dimension: false
        is_dynamic_dimension: false
      }
    }
    metadata {
    }
    id: 25
    operand_ids: 24
    frontend_attributes {
    }
  }
  program_shape {
    parameters {
      element_type: BF16
      dimensions: 1
      dimensions: 1
      dimensions: 2048
      layout {
        minor_to_major: 2
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    parameters {
      element_type: BF16
      dimensions: 128
      dimensions: 192
      dimensions: 2048
      layout {
        minor_to_major: 2
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    parameters {
      element_type: BF16
      dimensions: 128
      dimensions: 2048
      dimensions: 384
      layout {
        minor_to_major: 2
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    parameters {
      element_type: F32
      dimensions: 128
      dimensions: 2048
      layout {
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
    parameters {
      element_type: BF16
      dimensions: 2048
      layout {
        minor_to_major: 0
      }
      is_dynamic_dimension: false
    }
    result {
      element_type: TUPLE
      tuple_shapes {
        element_type: BF16
        dimensions: 1
        dimensions: 1
        dimensions: 2048
        layout {
          minor_to_major: 2
          minor_to_major: 1
          minor_to_major: 0
        }
        is_dynamic_dimension: false
        is_dynamic_dimension: false
        is_dynamic_dimension: false
      }
    }
    parameter_names: "p0"
    parameter_names: "p1"
    parameter_names: "p2"
    parameter_names: "p3"
    parameter_names: "p4"
  }
  id: 26
  root_id: 25
}
host_program_shape {
  parameters {
    element_type: BF16
    dimensions: 1
    dimensions: 1
    dimensions: 2048
    layout {
      minor_to_major: 2
      minor_to_major: 1
      minor_to_major: 0
    }
    is_dynamic_dimension: false
    is_dynamic_dimension: false
    is_dynamic_dimension: false
  }
  parameters {
    element_type: BF16
    dimensions: 128
    dimensions: 192
    dimensions: 2048
    layout {
      minor_to_major: 2
      minor_to_major: 1
      minor_to_major: 0
    }
    is_dynamic_dimension: false
    is_dynamic_dimension: false
    is_dynamic_dimension: false
  }
  parameters {
    element_type: BF16
    dimensions: 128
    dimensions: 2048
    dimensions: 384
    layout {
      minor_to_major: 2
      minor_to_major: 1
      minor_to_major: 0
    }
    is_dynamic_dimension: false
    is_dynamic_dimension: false
    is_dynamic_dimension: false
  }
  parameters {
    element_type: F32
    dimensions: 128
    dimensions: 2048
    layout {
      minor_to_major: 1
      minor_to_major: 0
    }
    is_dynamic_dimension: false
    is_dynamic_dimension: false
  }
  parameters {
    element_type: BF16
    dimensions: 2048
    layout {
      minor_to_major: 0
    }
    is_dynamic_dimension: false
  }
  result {
    element_type: TUPLE
    tuple_shapes {
      element_type: BF16
      dimensions: 1
      dimensions: 1
      dimensions: 2048
      layout {
        minor_to_major: 2
        minor_to_major: 1
        minor_to_major: 0
      }
      is_dynamic_dimension: false
      is_dynamic_dimension: false
      is_dynamic_dimension: false
    }
  }
  parameter_names: "p0"
  parameter_names: "p1"
  parameter_names: "p2"
  parameter_names: "p3"
  parameter_names: "p4"
}
id: 26
entry_computation_id: 26
stack_frame_index {
  file_names: "<stdin>"
  file_names: "/opt/aws_neuronx_venv_pytorch_2_9_nxd_inference/lib/python3.12/site-packages/neuronx_distributed_inference/utils/testing.py"
  file_names: "/opt/aws_neuronx_venv_pytorch_2_9_nxd_inference/lib/python3.12/site-packages/neuronx_distributed/trace/model_builder.py"
  file_names: "/opt/aws_neuronx_venv_pytorch_2_9_nxd_inference/lib/python3.12/site-packages/torch_neuronx/xla_impl/trace.py"
  file_names: "/opt/aws_neuronx_venv_pytorch_2_9_nxd_inference/lib/python3.12/site-packages/torch_neuronx/xla_impl/hlo_conversion.py"
  file_names: "/opt/aws_neuronx_venv_pytorch_2_9_nxd_inference/lib/python3.12/site-packages/torch/nn/modules/module.py"
  function_names: "<module>"
  function_names: "build_module"
  function_names: "trace"
  function_names: "_generate_hlo"
  function_names: "generate_hlo"
  function_names: "xla_trace"
  function_names: "_xla_trace"
  function_names: "_wrapped_call_impl"
  function_names: "_call_impl"
  file_locations {
    file_name_id: 1
    function_name_id: 1
    line: 12
  }
  file_locations {
    file_name_id: 2
    function_name_id: 2
    line: 264
  }
  file_locations {
    file_name_id: 3
    function_name_id: 3
    line: 576
  }
  file_locations {
    file_name_id: 3
    function_name_id: 4
    line: 904
  }
  file_locations {
    file_name_id: 4
    function_name_id: 5
    line: 460
  }
  file_locations {
    file_name_id: 5
    function_name_id: 6
    line: 601
  }
  file_locations {
    file_name_id: 5
    function_name_id: 7
    line: 387
  }
  file_locations {
    file_name_id: 6
    function_name_id: 8
    line: 1775
  }
  file_locations {
    file_name_id: 6
    function_name_id: 9
    line: 1786
  }
  stack_frames {
    file_location_id: 1
  }
  stack_frames {
    file_location_id: 2
    parent_frame_id: 1
  }
  stack_frames {
    file_location_id: 3
    parent_frame_id: 2
  }
  stack_frames {
    file_location_id: 4
    parent_frame_id: 3
  }
  stack_frames {
    file_location_id: 5
    parent_frame_id: 4
  }
  stack_frames {
    file_location_id: 6
    parent_frame_id: 5
  }
  stack_frames {
    file_location_id: 7
    parent_frame_id: 6
  }
  stack_frames {
    file_location_id: 8
    parent_frame_id: 7
  }
  stack_frames {
    file_location_id: 9
    parent_frame_id: 8
  }
}
frontend_attributes {
  map {
    key: "transposable_weight_idx"
  }
}
